services:
  newsbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsbot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WP_BASE_URL=${WP_BASE_URL}
      - WP_USER=${WP_USER}
      - WP_PASSWORD=${WP_PASSWORD}
      - DAYS_INTERVAL=${DAYS_INTERVAL}
      - WEEKLY_DAY=${WEEKLY_DAY}
      - WEEKLY_TIME=${WEEKLY_TIME}
    volumes:
      - ./logs:/app/logs
