-- Migration 001: Initial schema for PreventIA News Analytics
-- Created: 2025-06-27
-- Description: Creates the basic tables for news sources, articles, and analytics

-- Enable UUID extension for better IDs (optional)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table: news_sources
-- Stores information about news sources that can be scraped
CREATE TABLE news_sources (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    base_url VARCHAR(500) NOT NULL UNIQUE,
    language VARCHAR(10) NOT NULL DEFAULT 'es',
    country VARCHAR(50) NOT NULL,
    extractor_class VARCHAR(255), -- Python class name for scraping
    is_active BOOLEAN DEFAULT true,
    validation_status VARCHAR(50) DEFAULT 'pending', -- pending, validated, failed
    validation_error TEXT,
    last_validation_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: articles
-- Stores scraped articles with enriched analytics data
CREATE TABLE articles (
    id SERIAL PRIMARY KEY,
    source_id INTEGER NOT NULL REFERENCES news_sources(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    url VARCHAR(1000) NOT NULL UNIQUE,
    content TEXT,
    summary TEXT,
    published_at TIMESTAMP NOT NULL,
    scraped_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Geographic and linguistic classification
    language VARCHAR(10),
    country VARCHAR(50),
    
    -- Sentiment analysis results
    sentiment_score DECIMAL(4,3), -- -1.000 to 1.000
    sentiment_label VARCHAR(20), -- positive, neutral, negative
    sentiment_confidence DECIMAL(3,2), -- 0.00 to 1.00
    
    -- Topic classification
    topic_category VARCHAR(50), -- prevention, treatment, diagnosis, testimonials, research
    topic_confidence DECIMAL(3,2), -- 0.00 to 1.00
    
    -- Processing metadata
    processing_status VARCHAR(50) DEFAULT 'pending', -- pending, processing, completed, failed
    processing_error TEXT,
    content_hash VARCHAR(64), -- SHA-256 hash for duplicate detection
    word_count INTEGER,
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: article_keywords
-- Stores extracted keywords and their relevance scores
CREATE TABLE article_keywords (
    id SERIAL PRIMARY KEY,
    article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    keyword VARCHAR(255) NOT NULL,
    relevance_score DECIMAL(3,2), -- 0.00 to 1.00
    keyword_type VARCHAR(50), -- medical_term, location, person, organization, etc.
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Prevent duplicate keywords per article
    UNIQUE(article_id, keyword)
);

-- Table: weekly_analytics
-- Pre-calculated analytics for dashboard performance
CREATE TABLE weekly_analytics (
    id SERIAL PRIMARY KEY,
    week_start DATE NOT NULL,
    week_end DATE NOT NULL,
    
    -- Article counts
    total_articles INTEGER DEFAULT 0,
    articles_by_language JSONB, -- {"es": 45, "en": 32}
    articles_by_country JSONB,  -- {"mexico": 25, "colombia": 15}
    articles_by_source JSONB,   -- {"1": 20, "2": 15} source_id: count
    articles_by_topic JSONB,    -- {"prevention": 30, "treatment": 25}
    
    -- Sentiment analysis
    sentiment_distribution JSONB, -- {"positive": 0.4, "neutral": 0.3, "negative": 0.3}
    avg_sentiment_score DECIMAL(4,3),
    
    -- Popular content
    top_keywords JSONB,           -- [{"keyword": "mamografia", "count": 15, "score": 0.95}]
    trending_topics JSONB,        -- Topics with significant growth
    
    -- AI-generated insights
    ai_summary TEXT, -- Weekly summary generated by LLM
    key_insights JSONB, -- Structured insights: [{"type": "trend", "description": "..."}]
    
    -- Metadata
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    articles_processed INTEGER DEFAULT 0,
    
    -- Ensure one record per week
    UNIQUE(week_start, week_end)
);

-- Performance indexes
CREATE INDEX idx_articles_published_at ON articles(published_at);
CREATE INDEX idx_articles_source_id ON articles(source_id);
CREATE INDEX idx_articles_sentiment ON articles(sentiment_label);
CREATE INDEX idx_articles_topic ON articles(topic_category);
CREATE INDEX idx_articles_country ON articles(country);
CREATE INDEX idx_articles_language ON articles(language);
CREATE INDEX idx_articles_status ON articles(processing_status);
CREATE INDEX idx_articles_hash ON articles(content_hash);

CREATE INDEX idx_keywords_article_id ON article_keywords(article_id);
CREATE INDEX idx_keywords_keyword ON article_keywords(keyword);
CREATE INDEX idx_keywords_type ON article_keywords(keyword_type);

CREATE INDEX idx_weekly_analytics_week ON weekly_analytics(week_start, week_end);

-- Function to update 'updated_at' timestamp automatically
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers for automatic timestamp updates
CREATE TRIGGER update_news_sources_updated_at BEFORE UPDATE ON news_sources
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_articles_updated_at BEFORE UPDATE ON articles
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Insert some initial news sources (existing ones from the project)
INSERT INTO news_sources (name, base_url, language, country, extractor_class, validation_status) VALUES
('Breast Cancer Org', 'https://www.breastcancer.org', 'en', 'United States', 'www_breastcancer_org', 'validated'),
('CureToday', 'https://www.curetoday.com', 'en', 'United States', 'www_curetoday_com', 'validated'),
('Medical Xpress', 'https://medicalxpress.com', 'en', 'International', 'medicalxpress_com', 'validated'),
('News Medical', 'https://www.news-medical.net', 'en', 'International', 'www_news_medical_net', 'validated'),
('Science Daily', 'https://www.sciencedaily.com', 'en', 'International', 'www_sciencedaily_com', 'validated'),
('WebMD', 'https://www.webmd.com', 'en', 'United States', 'www_webmd_com', 'validated'),
('Nature', 'https://www.nature.com', 'en', 'International', 'www_nature_com', 'validated'),
('Breast Cancer Now', 'https://breastcancernow.org', 'en', 'United Kingdom', 'breastcancernow_org', 'validated');

-- Comments for documentation
COMMENT ON TABLE news_sources IS 'News sources configuration for dynamic scraping';
COMMENT ON TABLE articles IS 'Scraped articles with NLP analysis results';
COMMENT ON TABLE article_keywords IS 'Extracted keywords from articles with relevance scores';
COMMENT ON TABLE weekly_analytics IS 'Pre-calculated weekly metrics for dashboard performance';

COMMENT ON COLUMN articles.content_hash IS 'SHA-256 hash of content for duplicate detection';
COMMENT ON COLUMN articles.sentiment_score IS 'Sentiment score from -1.0 (negative) to +1.0 (positive)';
COMMENT ON COLUMN weekly_analytics.ai_summary IS 'AI-generated summary of weekly trends and insights';